### ISSUE TITLE
How to get landmarks close to nodes on route

### ISSUE THREAD

**Issue by cdondrup** [LAAS-HRI/semantic-route-description#2]
Question, if I have a route like this:

```
route: [robot_infodesk, os_exp_1, gf_ww1_os1_intersection, gf_walkway_1, door_C, outside,
  ff_door_1, ff_corridor_4, burger_king]
```

how would I get any names of close by shops that could be used as landmarks? Just saying "turn left at door c" won't help most people. If there is a way to do that via ontologenius, I haven't found it yet.

**Comment by sarthou** [comment]
You can take a look at the package [route_verbalization](https://github.com/LAAS-HRI/route_verbalization) that verbalize this kind of routes with information like "turn left at door C".
This can be a good source of inspiration for you

**Comment by cdondrup** [comment]
OK, I since found that you can use object properties to do something similar. So I can do this to get all the shops along the corridor:

```
$ rosservice call /ontologenius/individual "action: 'select:getFrom'
param: 'shop=ff_corridor_4:isAlong'" 
values: [burger_king, hairstore, hiustalo]
code: 0
```

Is that how you would do this as well? So basically, I go through all the steps along the route and check if there are shops, etc.?

**Comment by sarthou** [comment]
1182/5000
OK, well, that's exactly what you need to use. The three [complex relationships](https://github.com/sarthou/ontologenius/wiki/Individuals-exploration#complex-relations) with the [select option](https://github.com/sarthou/ontologenius/wiki/Individuals-exploration#query-options) is the best way to get the information you need.

Indeed, go through all the stages of the course. Take a look at [this file](https://github.com/LAAS-HRI/route_verbalization/blob/master/src/mapManipulators/MapReader.cpp), that's exactly what it does to ragarger the shops along a corridor. That's why I can draw each path [like that](https://github.com/LAAS-HRI/route_verbalization#verification).

***

For corridors, stores can be defined:
- isAtRightOfPath
- isAtLeftOfPath
- isAtBeginEdgeOfPath
- isAtEndEdgeOfPath

For openspaces, they will be defined:
- isAlong

***

The origin is arbitrarily defined for each corridor. Once an origin has been defined (beginning and end), we simply define the stores to the right or left when we are at the beginning and we turn towards the end.
